version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r@#$$